implemented hi-all

diff --git a/bin/hi-all b/bin/hi-all
--- a/bin/hi-all
+++ b/bin/hi-all
@@ -41,40 +41,44 @@ source "${HI_CLI_HOME}/bin/version"
 source "${HI_CLI_HOME}/bin/usage"
 source "${HI_CLI_HOME}/bin/utils"
 
-modules=""
+function main() {
 
-module_conf="${HI_CLI_HOME}/modules/${module_name}/hi.conf"
-if [ -f "${module_conf}" ]; then
-  source "${module_conf}"
-fi
-#log_debug "${filter}"
-if [ "${filters}" != "" ]; then
   modules=""
-  array=($filters)
-  echo filters: $filters
-  for f in "${array[@]}" 
-  do
-    log_debug "ef: ${f}"
-    find_modules m "${f}"
-    modules="${modules} ${m}"
-    log_debug "modules: ${modules}"
-  done
+  module_conf="${HI_CLI_HOME}/modules/${module_name}/hi.conf"
+  work_conf="${PWD}/hi.conf"
+  if [ -f "${work_conf}" ]; then
+    source "${work_conf}"
+  elif [ -f "${module_conf}" ]; then
+    source "${module_conf}"
+  fi
 
-  if [ "${modules}" == "" ]; then
-    log_info "No module found!"
+  if [ "${filters}" != "" ]; then
+    modules=""
+    array=($filters)
+    echo filters: $filters
+    for f in "${array[@]}" 
+    do
+      log_debug "ef: ${f}"
+      find_modules m "${f}"
+      modules="${modules} ${m}"
+      log_debug "current modules: ${modules}"
+    done
+    # log_debug "found modules: ${modules}"
+
+    if [ "${modules}" == "" ]; then
+      log_info "No module found!"
+      exit
+    fi
+
+  else
+    log_warn "filters is not found in hi.conf"
     exit
   fi
 
-else
-  log_error "filters is not found in hi.conf"
-  exit
-fi
+  app="hi"
 
-app="hi"
+  log_info "Running: ${CMD_LINE}"
 
-log_info "Running: ${CMD_LINE}"
-
-function main() {
   custom_module="${HI_CLI_HOME}/modules/${module_name}/${submodule_name}"
   module_cmd=${CMD_LINE}
   if [ -f "${custom_module}" ]; then
@@ -89,7 +93,15 @@ function main() {
 
   module_cmd=${module_cmd/hi_debug/}
 
-  log_debug "modules: ${modules}"
+  cmd=$(echo "${module_cmd}" | awk '{print $1}')
+  log_debug "cmd: ${cmd}"
+
+  which ${cmd}
+  if [ $? == 1 ]; then
+    module_cmd="hi ${module_cmd}"
+  fi
+  log_debug "module_cmd: ${module_cmd}"
+
   for module in ${modules} 
   do
     log_info "=> ${module}"
